spring.application.name=ems

spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=ems
spring.datasource.password=ems

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
